# ML-ZOOMCAMP MODULE 03 -HOMEWORK03

# import packages

In [73]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [71]:
pd.set_option('max_colwidth', 1000)
pd.set_option("display.precision", 4)

# load data

In [3]:
path="https://raw.githubusercontent.com/alexeygrigorev/datasets/master/course_lead_scoring.csv"

In [4]:
dataset = pd.read_csv(path)

<br>
In this dataset our desired target for classification task will be converted variable - has the client signed up to the platform or not.
<br>
<br>

In [6]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1462 entries, 0 to 1461
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   lead_source               1334 non-null   object
 1   industry                  1328 non-null   object
 2   number_of_courses_viewed  1462 non-null   int64
 3   annual_income             1281 non-null   float64
 4   employment_status         1362 non-null   object
 5   location                  1399 non-null   object
 6   interaction_count         1462 non-null   int64
 7   lead_score                1462 non-null   float64
 8   converted                 1462 non-null   int64
dtypes: float64(2), int64(3), object(4)
memory usage: 102.9+ KB

In [5]:
dataset.head(5)

,lead_source,industry,number_of_courses_viewed,annual_income,employment_status,location,interaction_count,lead_score,converted
0,paid_ads,NaN,1,79450.0,unemployed,south_america,4,0.93999999999999994671,1
1,social_media,retail,1,46992.0,employed,south_america,1,0.80000000000000004441,0
2,events,healthcare,5,78796.0,unemployed,australia,3,0.68999999999999994671,1
3,paid_ads,retail,2,83843.0,NaN,australia,1,0.86999999999999999556,0
4,referral,education,3,85012.0,self_employed,europe,3,0.61999999999999999556,1

In [7]:
dataset.isnull().sum()

lead_source                 128
industry                    134
number_of_courses_viewed      0
annual_income               181
employment_status           100
location                     63
interaction_count             0
lead_score                    0
converted                     0
dtype: int64

In [8]:
df=dataset.copy()

In [116]:
categorical_columns = list(df.dtypes[df.dtypes == 'object'].index)

numerical_columns=list(df.dtypes[df.dtypes=='float64'].index)

for a in list(df.dtypes[df.dtypes=='int64'].index):
    numerical_columns.append(a)
    

print("categorical_columns:",categorical_columns)
print("numerical_columns:",numerical_columns)

categorical_columns: ['lead_source', 'industry', 'employment_status', 'location']
numerical_columns: ['annual_income', 'lead_score', 'number_of_courses_viewed', 'interaction_count', 'converted']

In [33]:
for var in df.columns:
    
    if df[var].dtypes== 'object':
        df[var]=df[var].fillna(value='NA')   

    else:
        df[var]=df[var].fillna(value=0)

lead_source
industry
number_of_courses_viewed
annual_income
employment_status
location
interaction_count
lead_score
converted

"\nfor var in categorical_columns:\n\n    if df[var].isnull().sum()>0:\n        df[var]=df[var].fillna(value='NA')\n"

In [35]:
df.isnull().sum()

lead_source                 0
industry                    0
number_of_courses_viewed    0
annual_income               0
employment_status           0
location                    0
interaction_count           0
lead_score                  0
converted                   0
dtype: int64

In [36]:
df.shape

(1462, 9)

In [37]:
df.describe()

,number_of_courses_viewed,annual_income,interaction_count,lead_score,converted
count,1462.00000000000000000000,1462.00000000000000000000,1462.00000000000000000000,1462.00000000000000000000,1462.00000000000000000000
mean,2.03146374829001352680,52472.17236662106734002009,2.97674418604651158660,0.50610807113543099245,0.61901504787961691978
std,1.44971678595000108558,24254.34703032839752268046,1.68156434906455110045,0.28846540429698358521,0.48579505856345700510
min,0.00000000000000000000,0.00000000000000000000,0.00000000000000000000,0.00000000000000000000,0.00000000000000000000
25%,1.00000000000000000000,44097.25000000000000000000,2.00000000000000000000,0.26250000000000001110,0.00000000000000000000
50%,2.00000000000000000000,57449.50000000000000000000,3.00000000000000000000,0.51000000000000000888,1.00000000000000000000
75%,3.00000000000000000000,68241.00000000000000000000,4.00000000000000000000,0.75000000000000000000,1.00000000000000000000
max,9.00000000000000000000,109899.00000000000000000000,11.00000000000000000000,1.00000000000000000000,1.00000000000000000000

In [39]:
df.groupby("industry")["industry"].count().sort_values(ascending=False)

industry
retail           203
finance          200
other            198
education        187
healthcare       187
technology       179
manufacturing    174
NA               134
Name: industry, dtype: int64

## Question 2
<br>
Create the correlation matrix for the numerical features of your dataset. In a correlation matrix, you compute the correlation coefficient between every pair of features.
<br>
<br>
What are the two features that have the biggest correlation?
<br><br>
* interaction_count and lead_score
* number_of_courses_viewed and lead_score
* number_of_courses_viewed and interaction_count
* annual_income and interaction_count
<br><br>
Only consider the pairs above when answering this question.

In [72]:

df[numerical_columns].corr().round(4)

,annual_income,lead_score,number_of_courses_viewed,interaction_count,converted
annual_income,1.0000,0.0156,0.0098,0.0270,0.0531
lead_score,0.0156,1.0000,-0.0049,0.0099,0.1937
number_of_courses_viewed,0.0098,-0.0049,1.0000,-0.0236,0.4359
interaction_count,0.0270,0.0099,-0.0236,1.0000,0.3746
converted,0.0531,0.1937,0.4359,0.3746,1.0000

* annual_income and interaction_count 0.0270
* number_of_courses_viewed and interaction_count -0.0236
* interaction_count and lead_score 0.0099
* number_of_courses_viewed and lead_score  -0.0049

## Split the data
Split your data in train/val/test sets with 60%/20%/20% distribution.
Use Scikit-Learn for that (the train_test_split function) and set the seed to 42.
Make sure that the target value converted is not in your dataframe.

In [75]:
df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=1)
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=1)

In [78]:
print('total',df.shape)
print('full train',df_full_train.shape)
print('train',df_train.shape)
print('val',df_val.shape)
print('test',df_test.shape)

print('---')
print('total:',df.shape[0])
print('train',df.shape[0]*0.6)
print('val',df.shape[0]*0.2)
print('test',df.shape[0]*0.2)

total (1462, 9)
full train (1169, 9)
train (876, 9)
val (293, 9)
test (293, 9)
---
total: 1462
train 877.1999999999999
val 292.40000000000003
test 292.40000000000003

In [79]:
df_full_train = df_full_train.reset_index(drop=True)
df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

In [81]:
y_full_train = df_full_train.converted.values
y_train = df_train.converted.values
y_val = df_val.converted.values
y_test = df_test.converted.values

del df_full_train['converted']
del df_train['converted']
del df_val['converted']
del df_test['converted']

## Question 3
Calculate the mutual information score between converted and other categorical variables in the dataset. Use the training set only.
Round the scores to 2 decimals using round(score, 2).
Which of these variables has the biggest mutual information score?
<br><br>
* industry
* industrylocation
* industrylead_source
* industryemployment_status

In [82]:
from sklearn.metrics import mutual_info_score

In [88]:
for var in   categorical_columns:
    print("converted vs ", var, ": ", round(mutual_info_score(y_train, df_train[var]), 5))

converted vs  lead_source :  0.0248
converted vs  industry :  0.00616
converted vs  employment_status :  0.01634
converted vs  location :  0.00145

## Question 4

Now let's train a logistic regression.
<br>
<br>
Remember that we have several categorical variables in the dataset. Include them using one-hot encoding.
<br>
Fit the model on the training dataset.
<br>
To make sure the results are reproducible across different versions of Scikit-Learn, fit the model with these parameters:

<br>
- model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)
<br><br>
Calculate the accuracy on the validation dataset and round it to 2 decimal digits.
<br>
<br>
What accuracy did you get?

* 0.64
* 0.74
* 0.84
* 0.94

In [147]:
print(numerical_columns)

['annual_income', 'lead_score', 'number_of_courses_viewed', 'interaction_count']

In [148]:
numerical_columns.remove('converted')

ValueError: list.remove(x): x not in list

In [149]:
dicts = df_train[categorical_columns].to_dict(orient='records')
dicts=""

In [150]:
from sklearn.feature_extraction import DictVectorizer
 
train_dicts = df_train[categorical_columns + numerical_columns].to_dict(orient='records')
dv = DictVectorizer(sparse=False)
 
dv.fit(train_dicts)
X_train = dv.transform(train_dicts)
# instead of last two lines, you can also use
# X_train = dv.fit_transform(train_dicts)
 
X_train.shape

(876, 31)

In [151]:
val_dicts = df_val[categorical_columns + numerical_columns].to_dict(orient='records')
X_val = dv.transform(val_dicts)

In [152]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000, random_state=42, solver='liblinear')

In [132]:
#model.coef_[0].round(5)
#model.intercept_
#model.predict(X_train)
#model.predict_proba(X_train)

In [162]:
#applying to validation set
y_pred = model.predict_proba(X_val)[:,1]
y_pred
print("")

In [163]:
converted_decision = y_pred >0.5

In [171]:
accuracy_general=(y_val == converted_decision.astype(int)).mean()

accuracy_general

np.float64(0.6996587030716723)

## Question 5
Let's find the least useful feature using the feature elimination technique.
Train a model using the same features and parameters as in Q4 (without rounding).
Now exclude each feature from this set and train a model without it. Record the accuracy for each model.
For each feature, calculate the difference between the original accuracy and the accuracy without the feature.
Which of following feature has the smallest difference?

'industry'
'employment_status'
'lead_score'
Note: The difference doesn't have to be positive.

In [172]:
all_columns=numerical_columns + categorical_columns
all_columns

['annual_income',
 'lead_score',
 'number_of_courses_viewed',
 'interaction_count',
 'lead_source',
 'industry',
 'employment_status',
 'location']

In [178]:
acuracy_sin=[]
diff_accuracy=[]

for var in all_columns:

    try:
    # Code that might raise an error
        numerical_columns2=numerical_columns.remove(var)
    except:
         numerical_columns2= numerical_columns


    try:
    # Code that might raise an error
        categorical_columns2=categorical_columns.remove(var)
    except:
        categorical_columns2=categorical_columns
    
    
    from sklearn.feature_extraction import DictVectorizer
 
    train_dicts = df_train[categorical_columns2 + numerical_columns2].to_dict(orient='records')
    dv = DictVectorizer(sparse=False)
     
    dv.fit(train_dicts)
    X_train = dv.transform(train_dicts)
    # instead of last two lines, you can also use
    # X_train = dv.fit_transform(train_dicts)
     
    X_train.shape
    
    val_dicts = df_val[categorical_columns2 + numerical_columns2].to_dict(orient='records')
    X_val = dv.transform(val_dicts)
    
    from sklearn.linear_model import LogisticRegression
    
    model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)
    model.fit(X_train, y_train)
    
    y_pred = model.predict_proba(X_val)[:,1]
    y_pred
    print("")
    
    converted_decision = y_pred >0.5
    
    acc=(y_val == converted_decision.astype(int)).mean()
    acuracy_sin.append(acc)
    diff_accuracy.append(accuracy_general-acc)

TypeError: can only concatenate list (not "NoneType") to list

Question 6
Now let's train a regularized logistic regression.
Let's try the following values of the parameter C: [0.01, 0.1, 1, 10, 100].
Train models using all the features as in Q4.
Calculate the accuracy on the validation dataset and round it to 3 decimal digits.
Which of these C leads to the best accuracy on the validation set?

0.01
0.1
1
10
100
Note: If there are multiple options, select the smallest C.